
#docker build -t kontainer:dev -f ./Dockerfile-alpine --progress=plain . && \
#docker run -it --rm \
#  --name kontainer-dev \
#  -p 3080:3080 \
#  -p 3443:3443 \
#  -p 5000:5000 \
#  -v /var/run/docker.sock:/var/run/docker.sock \
#  -v /var/lib/docker/volumes:/var/lib/docker/volumes:ro \
#  -v kontainer_dev_data:/app/data \
#  -e KONTAINER_DATA_VOLUME=kontainer_dev_data \
#  kontainer:dev $@

services:
  kontainer-dev:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: kontainer:dev
    container_name: kontainer-dev
    ports:
      - "3080:3080"
      - "3443:3443"
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - kontainer_dev_data:/app/data
    environment:
      - KONTAINER_DATA_VOLUME=kontainer_dev_data
    profiles:
      - dev


  kontainer-latest:
    image: fmlabs/kontainer:latest
    container_name: kontainer-latest
    pull_policy: always
    restart: always
    ports:
      - "3443:3443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - kontainer_latest_data:/app/data
    environment:
      - KONTAINER_DATA_VOLUME=kontainer_latest_data
    profiles:
      - latest