
#docker run -d \
#  --restart always \
#  -p 3443:3443 \
#  -v /var/run/docker.sock:/var/run/docker.sock:ro \
#  -v /var/lib/docker/volumes:/var/lib/docker/volumes:ro \
#  -v kontainer_data:/app/data \
#  -e KONTAINER_DATA_VOLUME=kontainer_data \
#  fmlabs/kontainer:latest

services:

  kontainer:
    image: fmlabs/kontainer:latest
    restart: always
    ports:
      - "3443:3443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - kontainer_data:/app/data
    environment:
      - KONTAINER_DATA_VOLUME=kontainer_data


volumes:
  kontainer_data:
    driver: local