## Build stage
FROM node:22-alpine AS ui-builder

WORKDIR /app

# Copy package.json and yarn.lock for caching purposes
COPY ./ui/package.json ./ui/yarn.lock ./

# Install packages and cache them
RUN yarn install --frozen-lockfile --network-timeout 600000 && yarn cache clean

# Copy rest of files
# See / edit .dockerignore file for excluded files
COPY ./ui/ /app/
RUN ls -la /app

RUN yarn build


## Assembly stage
FROM scratch AS assembly-stage

WORKDIR /

# Copy the application code
COPY ./core/pyproject.toml ./core/poetry.lock /app/
COPY ./core/bin /app/bin
COPY ./core/src /app/src
COPY ./core/main.py /app/main.py
COPY ./core/celery_worker.sh /app/celery_worker.sh

# Copy frontend app from the ui-builder stage
COPY --from=ui-builder /app/dist /app/www

# Configure Nginx
COPY ./core/docker/alpine/nginx/nginx.conf /etc/nginx/nginx.conf
#COPY ./core/docker/nginx/site.default.conf /etc/nginx/http.d/default.conf
COPY ./docker/nginx/site.ssl.conf /etc/nginx/http.d/default.conf

# Configure Supervisor
COPY ./core/docker/alpine/supervisor/supervisord.conf /etc/supervisord.conf
COPY ./core/docker/supervisor/celery_worker.ini /etc/supervisor.d/celery_worker.ini
COPY ./core/docker/supervisor/redis.ini /etc/supervisor.d/redis.ini
COPY ./core/docker/supervisor/nginx.ini /etc/supervisor.d/nginx.ini
COPY ./core/docker/supervisor/app.ini /etc/supervisor.d/app.ini



## Production stage
FROM python:3.13-alpine3.22
LABEL maintainer="fm-labs <flowmotionlabs@gmail.com>"
LABEL description="This is the production image for the kontainer service"

ENV KONTAINER_HOST=0.0.0.0
ENV KONTAINER_PORT=5000

ARG DOCKER_DIR=/var/lib/docker
ARG DOCKER_COMPOSE_VERSION=2.37.3

# Install os packages
RUN apk update && apk add --no-cache \
    bash \
    curl \
    nginx \
    redis \
    supervisor \
    openssl \
    docker-cli \
    git \
    aws-cli \
    openssh


# Install poetry and other python dependencies
RUN pip install --no-cache-dir --upgrade pip poetry setuptools wheel


# Install docker-compose
RUN mkdir -p $DOCKER_DIR/cli-plugins && \
    ARCH=$(uname -m) && \
    COMPOSE_DOWNLOAD_URL=https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${ARCH} && \
    echo "COMPOSE_DOWNLOAD_URL=$COMPOSE_DOWNLOAD_URL" && \
    curl -SL --fail ${COMPOSE_DOWNLOAD_URL} -o $DOCKER_DIR/cli-plugins/docker-compose && \
    chmod +x $DOCKER_DIR/cli-plugins/docker-compose && \
    ln -s $DOCKER_DIR/cli-plugins/docker-compose /usr/local/bin/docker-compose


# Set a non-root user
# We add user to the 'ping' (gid: 999) group, which is a default group in the alpine image,
# and the equivalent of the 'docker' group in the ubuntu image,
# which is automatically created by the linux docker installer.
RUN addgroup -S appgroup && addgroup -S docker && \
    adduser -S appuser -G appgroup && \
    adduser appuser docker && \
    adduser appuser ping && \
    adduser appuser root

WORKDIR /app


# Install python dependencies
COPY ./core/pyproject.toml ./core/poetry.lock /app/
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --only main --no-root

# Copy frontend app from the ui-builder stage
COPY --from=assembly-stage /app /app
COPY --from=assembly-stage /etc/nginx /etc/nginx
COPY --from=assembly-stage /etc/supervisord.conf /etc/supervisord.conf
COPY --from=assembly-stage /etc/supervisor.d /etc/supervisor.d


# Change ownership to non-root user
RUN mkdir -p /etc/nginx/ssl/ && \
    mkdir -p /app/data/docker && \
    touch /app/data/docker/config && \
    mkdir -p /app/data/ssl && \
    mkdir -p /var/lib/redis && \
    mkdir -p /var/log/supervisor && \
    mkdir -p /var/log/nginx/ && \
    mkdir -p /var/log/redis && \
    touch /var/log/redis/redis.log && touch /run/redis/redis.pid && \
    touch /var/lib/nginx/logs/error.log && \
    touch /var/lib/nginx/logs/access.log && \
    chown -R appuser:appgroup /var/lib/nginx/logs/error.log && \
    chown -R appuser:appgroup /var/lib/nginx/logs/access.log && \
    chown -R appuser:appgroup /run && \
    chown -R appuser:appgroup /var/run && \
    chown -R appuser:appgroup /etc/supervisord.conf /etc/supervisor.d && \
    chown -R appuser:appgroup /etc/nginx/ssl && \
    chown -R appuser:appgroup /var/log/supervisor&& \
    chown -R appuser:appgroup /var/lib/nginx /var/lib/nginx/logs /run/nginx && \
    chown -R appuser:appgroup /var/lib/redis && \
    chown -R appuser:appgroup /var/log/redis/redis.log /run/redis/redis.pid && \
    chown -R appuser:appgroup /var/lib/docker/cli-plugins && \
    chown -R appuser:appgroup /usr/local/bin/docker-compose && \
    chown -R appuser:appgroup /app/data/ && \
    chown -R appuser:appgroup /app/data/docker && \
    chown -R appuser:appgroup /app/data/ssl


#ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
COPY ./core/docker/entrypoint-alpine.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["supervisor"]

# Health check
HEALTHCHECK --interval=60s --timeout=3s --retries=3 \
 CMD curl --fail http://localhost:${KONTAINER_PORT}/ || exit 1


#EXPOSE ${KONTAINER_PORT}
#EXPOSE 3080
EXPOSE 3443

USER appuser